{% set name = "xtb" %}
{% set version = "6.6.2b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/njzjz/xtb/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0b9ec28a2f79647a7ec54b9d06120c02d032b58b109e79b30f51f79d29470cfc

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('xtb', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - cmake <3.27
    - ninja
    - asciidoctor
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - libblas
    - liblapack
    - mctc-lib
    - tblite


test:
  commands:
    - xtb --version

about:
  home: https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/xtb
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Semiempirical Extended Tight-Binding Program Package
  doc_url: https://xtb-docs.readthedocs.io/
  dev_url: https://github.com/grimme-lab/xtb

extra:
  recipe-maintainers:
    - awvwgk
